---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: fix-encoding-pragma
            args: [--remove]
          - id: check-yaml
          - id: debug-statements
            language_version: python3
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.2.2
      hooks:
        - id: ruff-format
          args: ["--preview"]
        - id: ruff
    - repo: local
      hooks:
          - id: rst
            name: rst
            entry: rst-lint --encoding utf-8
            files: ^(CHANGES.rst|README.rst)$
            language: python
            additional_dependencies: [pygments, restructuredtext_lint]
